apiVersion: v1
kind: Service
metadata:
  name: statistics-api-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: statistics-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080