apiVersion: v1
kind: Service
metadata:
  name: device-registration-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: device-registration-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080